'use client'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'

export default function SignUpPage(){const [form,setForm]=useState({name:'',email:'',phone:'',remarks:'',password:'',invite:''});const [error,setError]=useState('');const [loading,setLoading]=useState(false);const router=useRouter();function update(key:string,value:string){setForm({...form,[key]:value})}async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');const supabase=createClient();const {data:valid}=await supabase.rpc('validate_invite_code',{candidate:form.invite.trim()});if(!valid){setError('That invite code is not valid.');setLoading(false);return}const {error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{emailRedirectTo:`${window.location.origin}/auth/callback`,data:{name:form.name,phone:form.phone,remarks:form.remarks}}});if(error)setError(error.code==='user_already_exists'?'Unable to create this account.':'Unable to create your account. Please check your details and try again.');else router.push('/auth/sign-up-success');setLoading(false)}return <main className="flex min-h-svh items-center justify-center bg-[#f5f7f4] px-5 py-10"><Card className="w-full max-w-md border-[#dbe7df] shadow-sm"><CardHeader><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#5c7d6a]">Rugby club bar</p><CardTitle className="text-2xl text-[#12372a]">Join the roster</CardTitle><CardDescription>Use the invite code from your club admin.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-4">{[['name','Name','text'],['email','Email','email'],['phone','Phone','tel'],['invite','Invite code','text'],['password','Password','password']].map(([key,label,type])=><div className="space-y-2" key={key}><Label htmlFor={key}>{label}</Label><Input id={key} type={type} required={key!=='phone'} value={form[key as keyof typeof form]} onChange={e=>update(key,e.target.value)} /></div>)}<div className="space-y-2"><Label htmlFor="remarks">Remarks <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea id="remarks" value={form.remarks} onChange={e=>update('remarks',e.target.value)} /></div>{error&&<p className="text-sm text-red-700">{error}</p>}<Button disabled={loading} className="w-full bg-[#185c3a] hover:bg-[#12482d]">{loading?'Creating account…':'Create account'}</Button><p className="text-center text-sm text-[#668070]">Already registered? <Link className="font-semibold text-[#185c3a] hover:underline" href="/auth/login">Sign in</Link></p></form></CardContent></Card></main>}
