'use client'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

export default function LoginPage() { const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const router=useRouter(); async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');const {error}=await createClient().auth.signInWithPassword({email,password});if(error)setError(error.code==='email_not_confirmed'?'Please confirm your email address before signing in.':error.code==='invalid_credentials'?'Invalid email or password.':'Something went wrong. Please try again.');else router.push('/app');setLoading(false)} return <AuthCard title="Welcome back" description="Sign in to coordinate the club bar."><form onSubmit={submit} className="space-y-5"><div className="space-y-2"><Label htmlFor="email">Email</Label><Input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="password">Password</Label><Input id="password" type="password" required value={password} onChange={e=>setPassword(e.target.value)} /></div>{error&&<p className="text-sm text-red-700">{error}</p>}<Button disabled={loading} className="w-full bg-[#185c3a] hover:bg-[#12482d]">{loading?'Signing in…':'Sign in'}</Button><p className="text-center text-sm"><Link className="font-semibold text-[#185c3a] hover:underline" href="/auth/forgot-password">Forgot your password?</Link></p><p className="text-center text-sm text-[#668070]">New to the club? <Link className="font-semibold text-[#185c3a] hover:underline" href="/auth/sign-up">Create an account</Link></p></form></AuthCard> }
function AuthCard({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <main className="flex min-h-svh items-center justify-center bg-[#f5f7f4] px-5 py-10"><Card className="w-full max-w-md border-[#dbe7df] shadow-sm"><CardHeader><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#5c7d6a]">Rugby club bar</p><CardTitle className="text-2xl text-[#12372a]">{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{children}</CardContent></Card> </main>}
